### ISSUE TITLE
Problem with prisma adapter, I suddenly have an 0auth callback error, and I'm in a loop of callbacks. 

### ISSUE THREAD

**Issue by Lean-98** [safak/next-blog#11]
Hi there! I'm facing some issue with the signin at 2:41:50 mark. As soon as I have inserted a prisma adapter, I suddenly have an 0auth callback error, and I'm in a loop of callbacks. 

http://localhost:3000/api/auth/signin?error=Callback

**Comment by karshdev** [comment]
@Lean-98 check your google cloud have you written exactly the same routes for providers https://localhost:3000/api/auth/callback/google

**Comment by mozi47** [comment]
check your google cloud and it will be same URI:
http://localhost:3000/api/auth/callback/google

in the .env make sure you have added NEXTAUTH_URL=http://localhost:3000,

clear the local storage and cookies.

**Comment by Lean-98** [comment]
Thanks in the end I was able to solve it , the error was that I don't added the name to the database in the environment variable: DATABASE_URL="mongodb+srv://example:example@cluster0.8psrfxm.mongodb.net/blog?retryWrites=true&w=majority".
