### ISSUE TITLE
A server-side exception has occurred

### ISSUE THREAD

**Issue by MOHITH-2002** [safak/next-blog#20]
https://wonderwrit-vxph.vercel.app/
![Screenshot 2023-09-26 000700](https://github.com/safak/next-blog/assets/110193919/798f7d85-022e-4a97-b9ab-5a389b641a8b)

**Comment by trash369** [comment]
can i know how you fix it

**Comment by A-viralS** [comment]
hey @MOHITH-2002 ! I am facing the same error. Can you please share how you solved it? Thanks!
