### ISSUE TITLE
Deployment Failure on Vercel for /write Route with React Quill

### ISSUE THREAD

**Issue by FREDVUNI** [safak/next-blog#36]
Description:

I'm encountering a deployment failure on Vercel specifically related to the /write route in my Next.js application. The /write route utilizes the React Quill package and seems to be causing issues during deployment.

Steps to Reproduce:

Attempt deployment on Vercel.
Observe the deployment logs or error messages specifically related to the /write route.

Expected Behavior:
The deployment on Vercel should proceed successfully for all routes, including the /write route using React Quill.

Actual Behavior:
The deployment breaks or encounters errors specifically when handling the /write route, causing the deployment to fail on Vercel.

**Comment by Bdisha123** [comment]
> Description:
> 
> I'm encountering a deployment failure on Vercel specifically related to the /write route in my Next.js application. The /write route utilizes the React Quill package and seems to be causing issues during deployment.
> 
> Steps to Reproduce:
> 
> Attempt deployment on Vercel. Observe the deployment logs or error messages specifically related to the /write route.
> 
> Expected Behavior: The deployment on Vercel should proceed successfully for all routes, including the /write route using React Quill.
> 
> Actual Behavior: The deployment breaks or encounters errors specifically when handling the /write route, causing the deployment to fail on Vercel.

have you found the solution..??? kindly reply

**Comment by FREDVUNI** [comment]
Sorry for the late reply but yeah, I found the solution. It was the IP Address.

Here's the link to the [solution](https://github.com/vercel/next.js/discussions/63054) and better context
