### ISSUE TITLE
Error: data?.map is not a function.. 

### ISSUE THREAD

**Issue by ratneshpawar1** [safak/next-blog#38]
![ff](https://github.com/safak/next-blog/assets/79210935/8cfd6b61-0a93-420c-94b2-ec18b2c83178)

I tried many alternatives from the internet,
not able to pin down the issue and I believe its to do with route.js but not able to solve this issue.

Can someone suggest?

**Comment by satyamgit1** [comment]
when i also try to run the project its showing the same, if you find something please let me know

**Comment by ratneshpawar1** [comment]
Hi Satyam,
I was able to solve the issue.
![Screenshot 2024-02-11 115714](https://github.com/safak/next-blog/assets/79210935/d8a87a3b-9fc6-4144-8380-8c87f92eb41e)

note: at line 19  Change  "const data to "const {data}" ( as shown in the screenshot)
